# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-19 02:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('poke_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='poke',
            old_name='alias',
            new_name='person_being_poked',
        ),
        migrations.RemoveField(
            model_name='poke',
            name='email',
        ),
        migrations.RemoveField(
            model_name='poke',
            name='name',
        ),
        migrations.RemoveField(
            model_name='poke',
            name='poke',
        ),
    ]
