# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-19 02:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('poke_app', '0002_auto_20171118_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='poke',
            name='poke_count',
            field=models.IntegerField(default=0),
        ),
    ]
