# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-25 17:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('poke_app', '0007_auto_20171119_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poke',
            name='person_being_poked',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pokee', to='login_app.User'),
        ),
    ]
